on: push
name: build
jobs:
  build:
    name: build cr-gcp
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: docker build
      run: |
        docker build . -t ${{secrets.REGISTRY_URL}}/${{secrets.GKE_PROJECT_ID }}/${{secrets.DOCKER_IMAGE_NAME}}:${GITHUB_SHA::8} -t ${{secrets.REGISTRY_URL}}/${{ secrets.GKE_PROJECT_ID }}/${{secrets.DOCKER_IMAGE_NAME}}:latest
        echo ${{secrets.GCP_KEY_FILE}} | base64 -d > account.json
        cat account.json | docker login -u _json_key --password-stdin https://${{secrets.REGISTRY_URL}}
        docker push ${{secrets.REGISTRY_URL}}/${{ secrets.GKE_PROJECT_ID }}/${{secrets.DOCKER_IMAGE_NAME}}
        docker logout
  